test002.c: 函数 `f' :
test002.c:6: エラー: 仮引数 `a' が再宣言されています.
test002.c:4: エラー: ここで宣言されていました.
