test005.c:8: エラー: `f' が再宣言されています.
test005.c:6: エラー: ここで宣言されていました.
test005.c: 函数 `g' :
test005.c:14: エラー: 函数 `f' の呼び出しの 1 番目の引数がマッチしません.
test005.c:18: エラー: 函数 `f' の呼び出しの 1 番目の引数がマッチしません.
