test004.c: 函数 `f' :
test004.c:11: エラー: `a' は宣言されていません.
test004.c: 函数 `g' :
test004.c:16: エラー: `b' は宣言されていません.
