test009.c: 函数 `test000' :
test009.c:8: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:7: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test001' :
test009.c:14: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:13: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test002' :
test009.c:20: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:19: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test003' :
test009.c:26: エラー: 単項の `&' が register 宣言されている `a' に指定されています.
test009.c:25: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test004' :
test009.c:32: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:31: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test006' :
test009.c:44: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:43: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test007' :
test009.c:50: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:49: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test008' :
test009.c:56: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:55: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test009' :
test009.c:62: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:61: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test010' :
test009.c:68: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:67: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test011' :
test009.c:74: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:73: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test012' :
test009.c:80: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:79: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test013' :
test009.c:86: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:85: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test014' :
test009.c:92: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:91: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test015' :
test009.c:98: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:97: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test016' :
test009.c:104: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:103: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test017' :
test009.c:110: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:109: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test018' :
test009.c:116: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:115: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test019' :
test009.c:122: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:121: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test020' :
test009.c:128: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:127: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test021' :
test009.c:134: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:133: エラー: `a' はここで register 宣言されています.
test009.c: 函数 `test022' :
test009.c:140: エラー: register 宣言されている `a' のアドレスが参照されています.
test009.c:139: エラー: `a' はここで register 宣言されています.
