test001.c: 函数 `test000' :
test001.c:9: エラー: goto 文で.
test001.c:12: エラー: ここにジャンプしますが,
test001.c:11: エラー: `A' がここで宣言されています.
test001.c: 函数 `test001' :
test001.c:19: エラー: goto 文で.
test001.c:22: エラー: ここにジャンプしますが,
test001.c:21: エラー: `A' がここで宣言されています.
